service: sls-jwt-boilerplate

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${env:STAGE}
  region: ${env:REGION}

functions:
  hello:
    handler: handler.ping
    events:
      - http:
          path: ping
          method: get

  register:
    handler: handler.register
    events:
      - http:
          path: user/register
          method: post

  login:
    handler: handler.login
    events:
      - http:
          path: user/login
          method: post

  verify:
    handler: handler.verify
    events:
      - http:
          path: user/verify/{id}
          method: get
          request:
            parameters:
              paths:
                id: true

  reset:
    handler: handler.reset
    events:
      - http:
          path: user/reset
          method: post

  hidden:
    handler: handler.hidden
    events:
      - http:
          path: hidden/page
          method: get
          authorizer: auth

  auth:
    handler: controllers/auth.auth
