service: sls-jwt-boilerplate

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${env:STAGE}
  region: ${env:REGION}

functions:
  register:
    handler: handler.register
    events:
      - http:
          path: user/register
          method: post
  login:
    handler: handler.login
    events:
      - http:
          path: user/login
          method: post
  verify:
    handler: handler.verify
    events:
      - http:
          path: user/verify/{id}
          method: post
          request:
            parameters:
              paths:
                id: true
  reset:
    handler: handler.reset
    events:
      - http:
          path: user/reset
          method: post
  password:
    handler: handler.password
    events:
      - http:
          path: user/password
          method: put
  getScopes:
    handler: handler.getScopes
    events:
      - http:
          path: user/scopes/{id}
          method: get
          authorizer: authGetScopes
          request:
            parameters:
              paths:
                id: true
  addScope:
    handler: handler.addScope
    events:
      - http:
          path: user/scopes/{id}
          method: post
          authorizer: authAddScope
          request:
            parameters:
              paths:
                id: true
  removeScope:
    handler: handler.removeScope
    events:
      - http:
          path: user/scopes/{id}/{scopeName}
          method: delete
          authorizer: authRemoveScope
          request:
            parameters:
              paths:
                id: true
                scopeName: true
  getUserList:
    handler: handler.getUserList
    events:
      - http:
          path: user/list
          method: get
          authorizer: authGetUserList
  refreshToken:
    handler: handler.refreshToken
    events:
      - http:
          path: user/token/{id}
          method: put
          request:
            parameters:
              paths:
                id: true
  deleteuser:
    handler: handler.deleteUser
    events:
      - http:
          path: user/{id}
          method: delete
          authorizer: authDeleteUser
          request:
            parameters:
              paths:
                id: true
  lockUser:
    handler: handler.lockUser
    events:
      - http:
          path: user/lock/{id}
          method: put
          authorizer: authLockUser
          request:
            parameters:
              paths:
                id: true
  authGetScopes:
    handler: service/Auth.getScopes

  authAddScope:
    handler: service/Auth.addScope

  authRemoveScope:
    handler: service/Auth.removeScope

  authGetUserList:
    handler: service/Auth.getUserList

  authDeleteUser:
    handler: service/Auth.deleteUser

  authLockUser:
    handler: service/Auth.lockUser
