service: kuka-js

custom:
  serverless-offline:
    httpPort: 4000

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${env:STAGE}
  region: ${env:REGION}

functions:
  register:
    handler: handler.register
    events:
      - http:
          path: user/register
          method: post

  login:
    handler: handler.login
    events:
      - http:
          path: user/login
          method: post

  verify:
    handler: handler.verify
    events:
      - http:
          path: user/verify/{id}
          method: post
          request:
            parameters:
              paths:
                id: true

  reset:
    handler: handler.reset
    events:
      - http:
          path: user/reset
          method: post

  password:
    handler: handler.password
    events:
      - http:
          path: user/password
          method: put

  getScopes:
    handler: handler.getScopes
    events:
      - http:
          path: user/scopes
          method: get
          authorizer: authGetScopes

  addScope:
    handler: handler.addScope
    events:
      - http:
          path: user/scopes
          method: post
          authorizer: authAddScope

  removeScope:
    handler: handler.removeScope
    events:
      - http:
          path: user/scopes/{scopeName}
          method: delete
          authorizer: authRemoveScope
          request:
            parameters:
              paths:
                scopeName: true

  getUserList:
    handler: handler.getUserList
    events:
      - http:
          path: user/list
          method: get
          authorizer: authGetUserList

  getUserData:
    handler: handler.getUser
    events:
      - http:
          path: user
          method: get
          authorizer: authGetUserData

  refreshToken:
    handler: handler.refreshToken
    events:
      - http:
          path: user/token
          method: put

  deleteuser:
    handler: handler.deleteUser
    events:
      - http:
          path: user
          method: delete
          authorizer: authDeleteUser

  lockUser:
    handler: handler.lockUser
    events:
      - http:
          path: user/lock
          method: put
          authorizer: authLockUser

  authGetScopes:
    handler: Auth.getScopes

  authAddScope:
    handler: Auth.addScope

  authRemoveScope:
    handler: Auth.removeScope

  authGetUserList:
    handler: Auth.getUserList

  authGetUserData:
    handler: Auth.getUserData

  authDeleteUser:
    handler: Auth.deleteUser

  authLockUser:
    handler: Auth.lockUser
