name: kuka
env:
  AWS_KEY: ${{secrets.AWS_KEY}}
  AWS_SECRET: ${{secrets.AWS_SECRET}}
  DYNAMODB_ARN: ${{secrets.DYNAMODB_ARN}}
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
  GH_TOKEN: ${{secrets.GH_TOKEN}}
  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  COMMIT_RANGE: "${{github.event.before}}..${{github.event.after}}"
  STAGE: dev
  REGION: "eu-north-1"
  KUKA_DOMAIN: "api.kuka.kivi.ws"

on:
  push:
    branches:
      - main

jobs:
  core:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10, 12]
    env:
      TARGET: "packages/kuka-core"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          if .ci/build.sh $COMMIT_RANGE $TARGET; then echo "Building '$TARGET' ..." && cd $TARGET && scripts/ci.sh; else echo "No changes detected in '$TARGET'; skipping build."; fi

  serverless:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12]
    env:
      TARGET: "packages/kuka-serverless"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          if .ci/build.sh $COMMIT_RANGE $TARGET; then echo "Building '$TARGET' ..." && cd $TARGET && scripts/ci.sh; else echo "No changes detected in '$TARGET'; skipping build."; fi
