name: kuka
env:
  AWS_KEY: ${{secrets.AWS_KEY}}
  AWS_SECRET: ${{secrets.AWS_SECRET}}
  APIGW_KEY: ${{secrets.APIGW_KEY}}
  APIGW_SECRET: ${{secrets.APIGW_SECRET}}
  DYNAMODB_ARN: ${{secrets.DYNAMODB_ARN}}
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
  GH_TOKEN: ${{secrets.GH_TOKEN}}
  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  COMMIT_RANGE: "${{github.event.before}}..${{github.event.after}}"
  STAGE: ci
  REGION: "eu-north-1"
  KUKA_DOMAIN: "api.kuka.kivi.ws"
  TABLE_NAME: "kuka-users"
  VER_RECIPIENT: "nake89@gmail.com"
  VER_SENDER: "nake89@gmail.com"
  AUTO_SEND_PASSWORD_RESET_ID: "true"
  AUTO_VERIFY_MAIL: "true"
  JWT_SECRET: ${{secrets.JWT_SECRET}}
  EXPIRATION_TIME: "15min"
  KUKA_SERVICE_NAME: "kuka-ci-test"
  CERTIFICATE_ARN: ""
  FRONTEND_DOMAIN: "http://localhost:5000"

on:
  push:
    branches:
      - main

jobs:
  core:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12]
    env:
      TARGET: "packages/kuka-core"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          if .ci/build.sh $COMMIT_RANGE $TARGET; then echo "Building '$TARGET' ..." && cd $TARGET && scripts/ci.sh; else echo "No changes detected in '$TARGET'; skipping build."; fi

  serverless:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12]
    env:
      TARGET: "packages/kuka-serverless"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build and Test
        run: |
          if .ci/build.sh $COMMIT_RANGE $TARGET; then echo "Building '$TARGET' ..." && cd $TARGET && scripts/ci.sh; else echo "No changes detected in '$TARGET'; skipping build."; fi
      - name: Clean up table
        if: ${{ always() }}
        run: |
          node ./packages/kuka-serverless/scripts/delete-table.js
      - name: Clean up stack
        if: ${{ always() }}
        run: |
          cd $TARGET; ./node_modules/serverless/bin/serverless.js remove
